Rmadeye
labstructbioinf/dc2_oligo pull request #1
Opened 2023-08-22 09:28 UTC by Rmadeye

2023-08-22 20:06 UTC, jludwiczak requested changes
Looks good! Few general comments:
- Get rid of CV and train_test_split (fit whole dataset),
- Cleanup src dir, it's structure and imports,
- Predict with whole ensemble and report mean + stdev + argmax (already there),
- Reproducible env,
- Rest of minor things in comments.

2023-08-22 20:06 UTC, jludwiczak commented on README.md
> +pip install scikit-learn pandas joblib ...
I'm more in favor of specifying the conda yaml file with all dependencies and possibly their version.

2023-08-22 20:06 UTC, jludwiczak commented on README.md
> +pytest
`pytest` should be run from repo root I think, it'll discover tests in `test` directory and similar.

2023-08-22 20:06 UTC, jludwiczak commented on README.md
> +python src/predict.py --colabfold_output_dir tests/data/7 --use_pairwise True
Move it from src to repo root, it's more straightforward and common, alternatively keep it in source but make an entrypoint to run it as standalone script - e.g. https://github.com/labstructbioinf/localpdb/blob/master/pyproject.toml#L20-L21

2023-08-22 20:06 UTC, jludwiczak commented on src/data/set4_homooligomers.csv
Why `data` is kept in `src` ?

2023-08-22 20:06 UTC, jludwiczak commented on src/predict.py
> +sys.path.append(root_directory)
To dziala na mnie jak plachta na byka :D

2023-08-22 20:06 UTC, jludwiczak commented on src/results/model.p
Move away from src

2023-08-22 20:06 UTC, jludwiczak commented on tests/test_dc2.py
> +    assert result_2 == 1
This only checks whether predicted class is correct. It'd be good to check whether actual ensemble mean and stdev match too.

2023-08-22 20:06 UTC, jludwiczak commented on src/predict.py
> +    output = model.predict(X)[0]
Here you should compute ensemble mean and standard deviation and report them along with the classification result.

2023-08-22 20:06 UTC, jludwiczak commented on src/train.py
> +            X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2)
We want to fit on whole dataset for deployment model, split is not needed here.

2023-08-23 06:55 UTC, Rmadeye commented on README.md
> +pytest
It is in repo root, just suggested to first change dir into root directory after  cloning the repo

2023-08-23 08:34 UTC, Rmadeye commented on README.md
> +python src/predict.py --colabfold_output_dir tests/data/7 --use_pairwise True
Added

2023-08-24 08:00 UTC, merged