Dev
labstructbioinf/dc2_oligo pull request #2
Opened 2023-08-28 07:30 UTC by Rmadeye

-added docs to functions

2023-08-28 09:51 UTC, jludwiczak requested changes

2023-08-28 09:51 UTC, jludwiczak commented on README.md
> +| **`--use_pairwise`** | Flag for using sorting pair representations
Rephrase `Flag for using sorting pair representations`. Since this option is used by default maybe it can be omitted?

2023-08-28 09:51 UTC, jludwiczak commented on README.md
> +python predict.py --cf_results tests/data/0 --use_pairwise True --save_csv False
Bool flags can be set in `argparse` just using `--use_pairwise` instead of `--use_pairwise True`. Perhaps remove this if agreed to comment above. `--save_csv` can take a filename option.

2023-08-28 09:51 UTC, jludwiczak commented on analyze.ipynb
Rather not needed in main.

2023-08-28 09:51 UTC, jludwiczak commented on tests/data/0/3e7k.a3m
Remove this and other raw CF outputs that are not numpy matrices.

2023-08-28 09:51 UTC, jludwiczak commented on tests/test_dc2.py
> +sys.path.append(root_directory)
Still not addressed.

2023-08-28 09:51 UTC, jludwiczak commented on src/train.py
> +def get_x(id_: int, rank: int, model: str = "af2",
Are both get_x or get_af2_emb needed?

2023-08-28 09:51 UTC, jludwiczak commented on src/predictor.py
> +                'y_pred':y_pred_bin[0],}
Indentation.

2023-08-28 14:51 UTC, Rmadeye commented on src/train.py
> +def get_x(id_: int, rank: int, model: str = "af2",
nope

2023-08-29 14:48 UTC, jludwiczak approved these changes

2023-08-29 14:49 UTC, merged